# في مجلد مشروعك، أنشئ ملف render.yaml
services:
  - type: web
    name: e-shkalni-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
